name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://cloud189bj2.oos-bj2.ctyunapi.cn/PERSONCLOUD/8acd4b5c-8140-4203-8c43-8573fdf45749.zip?x-amz-CLIENTTYPEIN=UNKNOWN&AWSAccessKeyId=8d47af226f893e056f0c&x-amz-userLevel=0&x-amz-UID=588274965&x-amz-APPID=828221&response-content-disposition=attachment%3Bfilename%3D%22小米5S-Flyme8.zip%22%3Bfilename*%3DUTF-8%27%27%25E5%25B0%258F%25E7%25B1%25B35S-Flyme8.zip&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-CLOUDTYPEIN=PERSON&x-amz-limit=rate%3D5%2Cconcurrency%3D12&Signature=%2BLDHrUU8hg4924vHgnAJTYmXP2Q%3D&x-amz-SHID=1138312677789&Expires=1649395766&x-amz-FSIZE=1761208349&x-amz-UFID=51338315948782772
  ROM_NAME: Flyme
  BUILD_TYPE: aonly
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*
       
       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./final/GSI.zip

         
            
